//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biscotDATAaccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cartbl()
        {
            this.Drivertbls = new HashSet<Drivertbl>();
        }
    
        public int Id { get; set; }
        public string ModelKhodro { get; set; }
        public Nullable<long> VIN { get; set; }
        public string Pelak { get; set; }
        public string Rang { get; set; }
        public Nullable<int> SaleSakht { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Drivertbl> Drivertbls { get; set; }
    }
}
