//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biscotDATAaccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Triptbl
    {
        public int Id { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string StartLoc { get; set; }
        public string EndLoc { get; set; }
        public string StartLocName { get; set; }
        public string EndLocName { get; set; }
        public string Tozihat { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Drivertbl Drivertbl { get; set; }
        public virtual usertbl usertbl { get; set; }
    }
}
