//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biscotDATAaccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_report
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StartLocName { get; set; }
        public string EndLocName { get; set; }
        public string Tozihat { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Status { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string ModelKhodro { get; set; }
        public string Pelak { get; set; }
    }
}
