//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biscotDATAaccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_car
    {
        public Nullable<int> SaleSakht { get; set; }
        public string Rang { get; set; }
        public string Pelak { get; set; }
        public Nullable<long> VIN { get; set; }
        public string ModelKhodro { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long N_Code { get; set; }
        public string FatherName { get; set; }
        public Nullable<long> N_Id { get; set; }
        public string BirthdayDate { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public string Address { get; set; }
    }
}
